- name: Install and enable nginx and chrony services on AlmaLinux target machine
  hosts: VM2
  gather_facts: yes
  vars:
    test_var: nevin
  tasks:
    - name: Install nginx service on the target machine
      package:
        name: nginx
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution == 'AlmaLinux' 
        - test_var == "nevin"
    - name: Start and enable nginx service
      service:
        name: nginx
        enabled: yes
        state: started
      when:
        - ansible_host == "172.16.99.233"
        - ansible_hostname == "myfirstvm"   
        - test_var == "shahanas"  
    - name: Install Chrony service on the target machine
      package:
        name: chrony
        state: present
      when:
        - ansible_os_family == "RedHat"
        - ansible_host == "172.16.99.233"
    - name: Start and enable chrony service
      service:
        name: chronyd
        state: started
        enabled: yes      
      when:
        - ansible_distribution == "AlmaLinux"
        - ansible_architecture == "x86_64"   
        - ansible_user == "nthomas" 
